# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      build:
        patterns:
          - sass
          - "svelte"
          - "svelte-*"
          - "@sveltejs/*"
          - typescript
          - vite
      lint:
        patterns:
          - "prettier"
          - "prettier-*"
          - "stylelint"
          - "stylelint-*"
