name: Setup
description: "Setup Node.js and pnpm and install dependencies"

inputs:
  registry-url:
    description: "Registry URL to setup up for auth. Passed on to actions/setup-node."
    default: ""
  audit-level:
    description: "npm audit-level <info|low|moderate|high|critical|none>"
    default: "high"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        registry-url: ${{ inputs.registry-url }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Audit dependencies
      shell: bash
      run: pnpm audit --audit-level=${{ inputs.audit-level }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
