packages:
  - docs
  - manon
  - themes
  - examples/*
  - "!examples/tutorial"
  - icore_open_docs

overrides:
  cookie@<0.7.0: ">=0.7.0"
  devalue@<5.6.4: ">=5.6.4"
  devalue@<=5.6.3: ">=5.6.4"
  flatted@<3.4.0: ">=3.4.0"
  undici@>=7.0.0 <7.24.0: ">=7.24.0"
  undici@>=7.17.0 <7.24.0: ">=7.24.0"
