name: Test Manon Sass Bundle

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-sass-bundle:
    name: Build sass bundle
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build themes
        working-directory: themes
        run: pnpm run build:themes

      - name: Verify build output
        run: |
          CSS_FILES=$(find themes/dist -name "manon.*.css" -type f)

          if [ -z "$CSS_FILES" ]; then
            echo "No CSS files found in themes/dist"
            exit 1
          fi

          echo "CSS files found:"
          echo "$CSS_FILES" | while read -r file; do
            echo "  - $file ($(du -h "$file" | cut -f1))"
          done
